<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>linkMyPublished</name>
   <tag></tag>
   <elementGuidId>f42602f2-40ef-47ca-a8e5-d400aa67a16c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-xpath='dashboard-section-myContent']/h2[@data-xpath='dashboard-header-myContent']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
