<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>threeDots_btn</name>
   <tag></tag>
   <elementGuidId>baf05914-8af2-4967-820d-a73d3bbb1392</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-xpath='dashboard-item'][${index}]//div[@class='menu_btn']</value>
   </webElementProperties>
</WebElementEntity>
