<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>answer_image_block</name>
   <tag></tag>
   <elementGuidId>62a4028d-99de-4e09-ac59-47e6a91240f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-xpath='edit-question-item'][${index}]//div[@data-xpath='answer-block']//div[@data-xpath='image-block']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-xpath='edit-question-item'][${index}]//div[@data-xpath='answer-block']//div[@data-xpath='image-block']</value>
   </webElementProperties>
</WebElementEntity>
