<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>choice_block</name>
   <tag></tag>
   <elementGuidId>c200c2a0-b3e5-473d-b4f6-86c11ab0486c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-xpath='edit-question-item'][${index1}]//div[@data-xpath='answer-block']//div[@data-xpath='additional-answer'][${index2}]//textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-xpath='edit-question-item'][${index1}]//div[@data-xpath='answer-block']//div[@data-xpath='additional-answer'][${index2}]//textarea</value>
   </webElementProperties>
</WebElementEntity>
