<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hint_image_block</name>
   <tag></tag>
   <elementGuidId>b0bcc547-1892-4b2c-bdb2-1418a565bcc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-xpath='edit-question-item'][${index}]//div[@data-xpath='hint-block']//div[@data-xpath='image-block']</value>
   </webElementProperties>
</WebElementEntity>
