<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>question_image_block</name>
   <tag></tag>
   <elementGuidId>6c93f6c6-f349-487c-ac8d-69a6cd482874</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-xpath='edit-question-item'][${index}]//div[@data-xpath='question-block']//div[@data-xpath='image-block']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-xpath='edit-question-item'][${index}]//div[@data-xpath='question-block']//div[@data-xpath='image-block']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-xpath='edit-question-item'][${index}]//div[@data-xpath='question-block']//div[@data-xpath='image-block']</value>
   </webElementProperties>
</WebElementEntity>
