<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_crop</name>
   <tag></tag>
   <elementGuidId>a16fc8cb-f349-4624-8c9c-754e01830aa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@role=&quot;cropperToolbar&quot;]/div/div[3]/div/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@role=&quot;cropperToolbar&quot;]/div/div[3]/div/button[1]</value>
   </webElementProperties>
</WebElementEntity>
