<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CropperBox</name>
   <tag></tag>
   <elementGuidId>a39ad8c3-f2c4-478f-a3ab-3bc35114872f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@role=&quot;cropperEditor&quot;]//div[@class='cropper-canvas']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@role=&quot;cropperEditor&quot;]//div[@class='cropper-canvas']/img</value>
   </webElementProperties>
</WebElementEntity>
