<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Publish</name>
   <tag></tag>
   <elementGuidId>93e25401-6e48-4efd-ae8a-b640ca38916b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-xpath</name>
      <type>Main</type>
      <value>editor-header-button-publish</value>
   </webElementProperties>
</WebElementEntity>
