<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NodeSubtitle</name>
   <tag></tag>
   <elementGuidId>82dc2766-7b4c-4737-8f11-5e0cc8903ddb</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-xpath</name>
      <type>Main</type>
      <value>editor-header-subtitle-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Подзаголовок</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[1]/div[@class=&quot;glob-bg-secondary-color&quot;]/div[@class=&quot;tests-editor-header&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;header-body bt-md-9 bt-sm-12&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;table-layout&quot;]/div[@class=&quot;table-cell fill top-align&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;bt-xl-8 bt-lg-10 bt-md-12&quot;]/form[@class=&quot;header-form&quot;]/div[@class=&quot;subtitle line&quot;]/div[@class=&quot;rl-input form-subtitle&quot;]/div[@class=&quot;edit-state&quot;]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
